### ISSUE TITLE
Error in setup server.

### ISSUE THREAD

**Issue by wuhongyewhy** [codeurjc-students/2019-VSCode4Teaching#106]
I want to setup the server alone in my computer, using the command:

> D:\program1\VSCode4Teaching>java -jar vscode4teaching-server-2.0.1.jar   --spring.datasource.url=jdbc:mysql://localhost:3406/vscode4teach --file.initialization=false --data.initialization=false --spring.jpa.hibernate.ddl-auto=create

The server run normally only when spring.jpa.hibernate.ddl-auto set to "create" or "create-drop". When set to others, such as "validate",  "update", or "none", the server errors and terminate. Wrong messages are:

> 2021-08-26 12:25:10.468  INFO 5484 --- [           main] o.h.h.i.QueryTranslatorFactoryInitiator  : HHH000397: Using ASTQueryTranslatorFactory
> 2021-08-26 12:25:10.832  WARN 5484 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1062, SQLState: 23000
> 2021-08-26 12:25:10.832 ERROR 5484 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : Duplicate entry 'admin@admin.com' for key 'UK_ob8kqyqqgmefl0aco34akdtpe'
> 2021-08-26 12:25:10.835 ERROR 5484 --- [           main] o.h.i.ExceptionMapperStandardImpl        : HHH000346: Error during managed flush [org.hibernate.exception.ConstraintViolationException: could not execute statement]
> 2021-08-26 12:25:10.843  INFO 5484 --- [           main] ConditionEvaluationReportLoggingListener :
> 
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
> 2021-08-26 12:25:10.852 ERROR 5484 --- [           main] o.s.boot.SpringApplication               : Application run failed
> 

The problem exists in 1.0.15 too. I have no knowledge about Java, and don't what to do next.

**Comment by diego-guerrero** [comment]
Good morning @wuhongyewhy.

Sorry for the delay in responding. Please, if you are interested, could you try using the latest version available?

If you were not able to upgrade, you can try to run the first time using create-drop, stop the server, change the property to validate and run it again. Note that this will delete the data you currently have stored in the database.

I look forward to your reply, thank you very much in advance.

**Comment by diego-guerrero** [comment]
Closed due to inactivity. If error is persisting, you can open a new updated issue in this repo.
