### ISSUE TITLE
【BUG】JWT Token does not begin with Bearer

### ISSUE THREAD

**Issue by xxyuze** [codeurjc-students/2019-VSCode4Teaching#113]
Error 404. {"timestamp":"2022-03-31T07:04:26.475+0000","status":404,"error":"Not Found","message":"No message available","path":"/api/v2/courses/4/exercises"}

**Comment by diego-guerrero** [comment]
Good morning @xxyuze.

Sorry for the delay in responding. Please could you give us more information about the bug? For example, what you were doing when it occurred, how many users were connected to the server at the time it occurred or how many courses have you created. Please also tell us in which version of VSCode4Teaching this bug has occurred.

Thank you very much in advance.

**Comment by diego-guerrero** [comment]
Closed due to inactivity. If error is persisting, you can open a new updated issue in this repo.
