### ISSUE TITLE
How could we signup as teacher?

### ISSUE THREAD

**Issue by janus-labs** [codeurjc-students/2019-VSCode4Teaching#129]
Hey guys,

When I signup as default I am student how can I become a teacher? 

@micaelgallego @ivchicano @arialdev  @diego-guerrero

**Comment by diego-guerrero** [comment]
Hello!

By default a user is a teacher when registering using another teacher's invitation, being this the only way to be a course teacher currently available through the VSCode4Teaching GUI.

However, it may be interesting to allow administrators to modify the role assignment of users. We take note of the suggestion.

Thank you very much!
