### ISSUE TITLE
PROBLEM: Cannot install required Liveshare extension

### ISSUE THREAD

**Issue by Fikoun** [codeurjc-students/2019-VSCode4Teaching#135]
Hello, if someone knows or maintains this package please help
I get prompted when logging in to get Liveshare. I proceed and infinite loading starts going. I dont think its doing anythink.. I also have the extension dowloaded manually. Is there some specific version of LS or is it just the old 4TEACH code its self?

Is this deprecated.. Am I doing something wrong?
Thank in advance

**Comment by diego-guerrero** [comment]
Hi @Fikoun !

The Visual Studio Code extension has been marked as deprecated and will be removed in VSCode4Teaching version 3.0.0, so it is no longer supported. The new version will make use of an Angular web application for interaction with the users' local file system, avoiding the mandatory use of VSCode.

Sorry for the inconvenience.
